### ISSUE TITLE
Android 11 无法加载

### ISSUE THREAD

**Issue by qiefeimao** [yunpian/yunpian-captcha-demo-android#1]
Android 11 无法加载，.showLoadingView(true)后，一直转圈圈。

**Comment by qiefeimao** [comment]
compileSdkVersion和targetSdkVersion设为30就不行，设为29就可以显示了。

**Comment by qiefeimao** [comment]
> Android 11 无法加载，.showLoadingView(true)后，一直转圈圈。

compileSdkVersion和targetSdkVersion设为30就不显示，设为29就能显示了。

**Comment by saibogoo** [comment]
也遇到这个问题了

**Comment by yzpure** [comment]
已更新SDK至1.5.0，见 #2
